container:
  image: ubuntu:18.04

test_task:
  test_script:
      - apt update
      - apt install git python3 python3-pip -y
      - git clone https://github.com/z1rubinaz1/python-test.git
      - cd python-test
      - python3 main.py
