dist: bionic

env:
  - TEST_ENVIRONMENT=primary
  - TEST_ENVIRONMENT=secondary
  - TEST_ENVIRONMENT=important
  - TEST_ENVIRONMENT=beta
  - TEST_ENVIRONMENT=trial


install:
  - echo "Test Environment:- $TEST_ENVIRONMENT"
  - sudo apt update
  - sudo apt install git python3 python3-pip -y


script:
  - git clone https://github.com/z1rubinaz1/python-test.git
  - cd python-test
  - python3 main.py