trigger:
- master

jobs:
- job: Test
  strategy:
    parallel: 7
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      sudo apt update
      sudo apt install git python3 python3-pip -y
      git clone https://github.com/z1rubinaz1/python-test.git
      cd python-test
      python3 main.py
    displayName: 'Testing'
