from selenium import webdriver
import time

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
driver = webdriver.Chrome("./chromedriver", chrome_options=chrome_options)



driver.get("https://www.feelingsurf.fr/login")
time.sleep(4)
driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div/div[1]/div/div/form/fieldset/div[1]/div/input').send_keys("rock6064")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="app"]/div/div[3]/div/div[1]/div/div/form/fieldset/div[2]/div/input').send_keys("mina38985")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="app"]/div/div[3]/div/div[1]/div/div/form/fieldset/div[3]/button').click()
time.sleep(7)
driver.get("https://www.feelingsurf.fr/surfbar")
time.sleep(3)
driver.find_element_by_xpath('//*[@id="content"]/div[2]/div[2]/div/div[1]/div/div/button').click()
print("Working...")
time.sleep(250)
print("Checking...")
time.sleep(201)
print("Working...")
time.sleep(250)
print("Checking...")
time.sleep(250)
print("Working...")
time.sleep(227)
print("Checking...")
time.sleep(250)
print("Working...")
time.sleep(250)
print("Processing...")
time.sleep(230)
print("Working...")
time.sleep(217)
print("Checking...")
time.sleep(257)
print("Working...")
time.sleep(221)
print("Checking...")
time.sleep(250)
print("Working...")
time.sleep(150)
print("Checking...")




print("Done :)")
driver.quit()
